apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: network-attachments.k8s.cni.cncf.io
spec:
  group: k8s.cni.cncf.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                config:
                  type: string
  scope: Cluster
  names:
    plural: network-attachments
    singular: network-attachment
    kind: NetworkAttachmentDefinition
    shortNames:
      - net-attach-def
