apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-flannel
  name: pod-access-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "update", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kube-flannel
  name: pod-access-binding
subjects:
- kind: ServiceAccount
  name: my-service-account
  namespace: kube-flannel
roleRef:
  kind: Role
  name: pod-access-role
  apiGroup: rbac.authorization.k8s.io
